// Generated by CoffeeScript 1.6.2
'use strict';
var mdApp;

mdApp = angular.module('mdApp', ['ngResource']).config([
  '$httpProvider', function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    return delete $httpProvider.defaults.headers.common['X-Requested-With'];
  }
]).run([
  '$rootScope', function($rootScope) {
    $rootScope.kill_event = function(e) {
      e.cancelBubble = true;
      e.stopPropagation();
      return e.preventDefault();
    };
    return $rootScope.corsproxy = function(css_url) {
      var m;

      m = css_url.match(/https?:\/\/(.+)/);
      if (!m) {
        return false;
      }
      return "http://www.corsproxy.com/" + m[1];
    };
  }
]);
